# Application

spring.application.name=payment-orchestration
server.port=8080

payment.provider.base-url=http://localhost:8080

payment.manual-review.high-value=3000
payment.manual-review.batch-size=20

payment.manual-review.queue.enrichment-concurrency=4
payment.manual-review.queue.enrichment-timeout-seconds=2

# Performance

server.compression.enabled=true
server.compression.mime-types=application/json,text/html,text/xml,text/plain,application/javascript,text/css
server.compression.min-response-size=1024

