package com.lz.paymentorchestration.entrypoint.http.error;

public enum ApiErrorCode {
    PAYMENT_NOT_FOUND,
    ORDER_NOT_FOUND,
    CUSTOMER_BLOCKED,
    ORDER_NOT_PENDING_PAYMENT,
    INVALID_PAYMENT_AMOUNT,
    PAYMENT_AMOUNT_MISMATCH,
    PAYMENT_AMOUNT_EXCEEDS_LIMIT,
    INVALID_PAYMENT_STATUS_TRANSITION,
    PAYMENT_NOT_FOUND_BY_PROVIDER,
    INTERNAL_ERROR
}